Asp.netCoreCRUD/Models/ErrorViewModel.cs
namespace Asp.netCoreCRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Asp.netCoreCRUD/Models/Task.cs
using System.ComponentModel.DataAnnotations;

namespace Asp.netCoreCRUD.Models
{
    public class Task
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
    }
}

Asp.netCoreCRUD/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace Asp.netCoreCRUD.Controllers
{
    public class ToDoController : Controller
    {
        /*private readonly MvcTaskContext _context;

        public ToDoController(MvctaskContext context)
        {
            _context = context;
        }*/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Asp.netCoreCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - To Do List</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ToDo" asp-action="Index">To Do list</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Asp.netCoreCRUD/Views/ToDo/Index.cshtml
@{
    ViewData["Title"] = "To Do List";
}

<h3 class="fw-bold text-white">Sample To Do List</h3>
<div class="division">
</div>
<div>
    <div>
        <input type="text" class="form-control input" placeholder="Write your task title here..." aria-label="Title" aria-describedby="addon-wrapping">
        <input type="text" class="form-control input" placeholder="Write down here the task description..." aria-label="Description" aria-describedby="addon-wrapping">
        <button type="button" class="btn btn-light input">Create task</button>
    </div>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">State</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Edit/Delete</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><input class="form-check-input mt-0" type="checkbox" value="" aria-label="Checkbox for following text input"></th>
      <td>Sample task 1</p></td>
      <td><p class="fst-italic text-muted">Sample description for task 1</p></td>
      <td><a href="#" class="text-decoration-none">Edit </a><a href="#" class="text-decoration-none"> Delete</a></td>
    </tr>
    <tr>
      <th scope="row"><input class="form-check-input mt-0" type="checkbox" value="" aria-label="Checkbox for following text input"></th>
      <td><p>Sample task 2</p></td>
      <td><p class="fst-italic text-muted">Sample description for task 2</p></td>
      <td><a href="#" class="text-decoration-none">Edit </a><a href="#" class="text-decoration-none"> Delete</a></td>
    </tr>
  </tbody>
</table>
</div>
<div class="division">
</div>

Asp.netCoreCRUD/Views/ToDo/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]!; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>